# Generated by Django 5.2.13 on 2026-04-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education'), ('certification', 'Certification'), ('project', 'Major Project')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mohamed Ashish Roshan', max_length=200)),
                ('title', models.CharField(default='Full-Stack Developer & Security Engineer', max_length=300)),
                ('tagline', models.TextField(default='Building enterprise-grade security platforms and full-stack applications')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('resume_url', models.CharField(blank=True, max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('years_experience', models.IntegerField(default=2)),
                ('projects_completed', models.IntegerField(default=4)),
                ('technologies_used', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Profile Info',
                'verbose_name_plural': 'Profile Info',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('cybersecurity', 'Cybersecurity'), ('fullstack', 'Full-Stack'), ('devops', 'DevOps'), ('ai', 'AI/ML'), ('desktop', 'Desktop App')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('maintained', 'Actively Maintained')], default='completed', max_length=20)),
                ('tech_stack', models.JSONField(default=list, help_text='List of technologies used')),
                ('features', models.JSONField(default=list, help_text='List of key features')),
                ('architecture', models.TextField(blank=True, help_text='Architecture description')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('demo_video_url', models.URLField(blank=True)),
                ('thumbnail', models.CharField(blank=True, help_text='Thumbnail image URL or path', max_length=500)),
                ('screenshots', models.JSONField(default=list, help_text='List of screenshot URLs')),
                ('modules_count', models.IntegerField(default=0)),
                ('api_endpoints', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('gradient_from', models.CharField(default='#6366f1', max_length=30)),
                ('gradient_to', models.CharField(default='#8b5cf6', max_length=30)),
            ],
            options={
                'ordering': ['order', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework'), ('database', 'Database'), ('devops', 'DevOps'), ('tool', 'Tool'), ('cloud', 'Cloud'), ('security', 'Security'), ('other', 'Other')], max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency level 0-100')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(blank=True, help_text='CSS color for the skill', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
